### ISSUE TITLE
Errors when trying to fetch module info via browsenpm

### ISSUE THREAD

**Issue by alexindigo** [3rd-Eden/npmjs#1]
Logs:

nodejs:

```
TypeError: Cannot read property '1' of null
    at simple (/www/node_modules/npm-registry/index.js:90:19)
    at map (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:88:44)
    at flowing (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:263:7)
    at next (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:325:5)
    at iterators (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:329:7)
    at flowing (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:260:71)
    at next (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:325:5)
    at Assignment.each (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:331:4)
    at iterate (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:259:12)
    at next (/www/node_modules/npm-registry/node_modules/mana/node_modules/assign/index.js:325:5)
```

Couchdb:

browsenpm

```
[info] [<0.4859.0>] 172.17.0.13 - - PUT /browsenpm/npmjs%2Fping%2F1406338440459 201
[info] [<0.4861.0>] 172.17.0.13 - - PUT /browsenpm/nodejitsu%2Fping%2F1406338440454 201
[info] [<0.4862.0>] 172.17.0.13 - - PUT /browsenpm/fullfat%2Fping%2F1406338440461 201
[info] [<0.4863.0>] 172.17.0.13 - - PUT /browsenpm/strongloop%2Fping%2F1406338440460 201
[info] [<0.4793.0>] 172.17.0.13 - - PUT /browsenpm/npmjsau%2Fping%2F1406338440455 201
[info] [<0.4794.0>] 172.17.0.13 - - PUT /browsenpm/npmjseu%2Fping%2F1406338440457 201
[info] [<0.4796.0>] 172.17.0.13 - - PUT /browsenpm/iriscouch%2Fping%2F1406338440466 201
```

npm-registry

```
[info] [<0.4660.0>] 172.17.0.9 - - GET /registry/_design/app/_show/package/beaker?pkg=beaker&version=latest 200
[info] [<0.4797.0>] 172.17.0.9 - - GET /registry/_design/app/_show/package/beaker?pkg=beaker 200
[error] [<0.4729.0>] OS Process Error <0.312.0> :: {not_found,
                                                    <<"document not found">>}
[info] [<0.4729.0>] 172.17.0.9 - - GET /registry/_design/app/_show/package/glob?pkg=glob 404
[info] [<0.4730.0>] 172.17.0.9 - - GET /registry/_design/app/_view/dependedUpon 200
```

back to browsenpm

```
[info] [<0.4805.0>] 172.17.0.14 - - HEAD /browsenpm 200
[info] [<0.4858.0>] 172.17.0.14 - - GET /browsenpm/_design/results 200
[info] [<0.340.0>] Starting index update for db: browsenpm idx: _design/results
[info] [<0.340.0>] Index update finished for db: browsenpm idx: _design/results
[info] [<0.4949.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22npmjsau%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjsau%22%5D&limit=2400 200
[info] [<0.4948.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22strongloop%22%2C%5B%5D%5D&descending=true&endkey=%5B%22strongloop%22%5D&limit=2400 200
[info] [<0.4950.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22npmjseu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjseu%22%5D&limit=2400 200
[info] [<0.4947.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22nodejitsu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22nodejitsu%22%5D&limit=2400 200
[info] [<0.4948.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22cnpmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22cnpmjs%22%5D&limit=2400 200
[info] [<0.4947.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22iriscouch%22%2C%5B%5D%5D&descending=true&endkey=%5B%22iriscouch%22%5D&limit=2400 200
[info] [<0.4950.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22fullfat%22%2C%5B%5D%5D&descending=true&endkey=%5B%22fullfat%22%5D&limit=2400 200
[info] [<0.4937.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22cnpmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22cnpmjs%22%5D&limit=2400 200
[info] [<0.4949.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/publish?startkey=%5B%22npmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjs%22%5D&limit=2400 200
[info] [<0.4936.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22npmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjs%22%5D&limit=2400 200
[info] [<0.4933.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22nodejitsu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22nodejitsu%22%5D&limit=2400 200
[info] [<0.4945.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22fullfat%22%2C%5B%5D%5D&descending=true&endkey=%5B%22fullfat%22%5D&limit=2400 200
[info] [<0.4946.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22iriscouch%22%2C%5B%5D%5D&descending=true&endkey=%5B%22iriscouch%22%5D&limit=2400 200
[info] [<0.4935.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22npmjseu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjseu%22%5D&limit=2400 200
[info] [<0.4866.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22strongloop%22%2C%5B%5D%5D&descending=true&endkey=%5B%22strongloop%22%5D&limit=2400 200
[info] [<0.4934.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/delta?startkey=%5B%22npmjsau%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjsau%22%5D&limit=2400 200
[info] [<0.4932.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22fullfat%22%2C%5B%5D%5D&descending=true&endkey=%5B%22fullfat%22%5D&limit=2400 200
[info] [<0.4927.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22npmjsau%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjsau%22%5D&limit=2400 200
[info] [<0.4929.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22npmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjs%22%5D&limit=2400 200
[info] [<0.4865.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22iriscouch%22%2C%5B%5D%5D&descending=true&endkey=%5B%22iriscouch%22%5D&limit=2400 200
[info] [<0.4930.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22cnpmjs%22%2C%5B%5D%5D&descending=true&endkey=%5B%22cnpmjs%22%5D&limit=2400 200
[info] [<0.4860.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22strongloop%22%2C%5B%5D%5D&descending=true&endkey=%5B%22strongloop%22%5D&limit=2400 200
[info] [<0.4928.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22npmjseu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22npmjseu%22%5D&limit=2400 200
[info] [<0.4926.0>] 172.17.0.14 - - GET /browsenpm/_design/results/_list/byRegistry/ping?startkey=%5B%22nodejitsu%22%2C%5B%5D%5D&descending=true&endkey=%5B%22nodejitsu%22%5D&limit=2400 200
```

Any idea why it could be?

Thank you.

**Comment by 3rd-Eden** [comment]
Im on vacation atm, ill take a look at this issue once I'm back. Thanks for reporting!

**Comment by alexindigo** [comment]
Thank you :)

I patched it like that for now:

```
  map: {
    simple: function simple(data) {
      return {
        name: data ? data[1] : '-empty-',
        description: data ? data[2] : '-empty-'
      };
    }
  }
```

But I'm yet to understand what it actually means :)

PS. Have fun :)

**Comment by alexindigo** [comment]
Got more information about this. It's happens during module resolution with `Packages.prototype.depended` endpoint, somehow `dependedUpon` gets null.

**Comment by 3rd-Eden** [comment]
@alexindigo Do you happen to know a module name which causes this?

**Comment by alexindigo** [comment]
I couldn't reproduce with any specific modules. It happened with certain conditions, I bump into the problem once in a while, but yet to figure out exact steps.

**Comment by 3rd-Eden** [comment]
Ok, i'm just going to assume that the changes I've made above resolve the issues. If you see these issues re-occurring please, do-reopen this topic.
